### ISSUE TITLE
环境配置成功，服务运行失败：BeanCreationException: Error creating bean with name 'resultExceptionHandler': Injection of autowired dependencies failed

### ISSUE THREAD

**Issue by Casper-ren** [coderabbit214/bibliothecarius#23]
按照readme文件，对config文件夹中的application.yaml以下几项（ MySQL配置，opanai key，Qdrant 服务地址， 存储配置）进行修改。然后启动服务后，运行几秒后报错退出。查看docker的log，可以看到springboot启动后报错，`INFO 7 --- [main] c.c.b.BibliothecariusApplication : No active profile set, falling back to 1 default profile: "default"`以及`WARN 7 --- [ main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resultExceptionHandler': Injection of autowired dependencies failed
`
然后就是`ERROR 7 --- [ main] o.s.boot.SpringApplication : Application run failed`
`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.servlet.multipart.max-file-size' in value "${spring.servlet.multipart.max-file-size}"`按照这个报错，应该是配置文件有问题导致的？但已经对教程中配置文件中的对应内容做了更改，而且max-file-size这个参数应该是原文件就默认写好的。

**Comment by coderabbit214** [comment]
@Casper-ren 看看配置文件名字是不是改了

**Comment by Casper-ren** [comment]
> 

是指把application-example改成application么，这个已经改了的

**Comment by coderabbit214** [comment]
mysql不可以直接写成127.0.0.1,写本机地址吧192.168.xx

**Comment by coderabbit214** [comment]
application.yaml
```yaml
spring:
  servlet:
    multipart:
      max-file-size: 30MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 
    url: jdbc:mysql://mysql:3306/ai_librarian?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username:
    hikari:
      max-lifetime: 100000

qdrant:
  host: http://qdrant:6333
```
docker-comose.yaml
```yaml
version: '3.3'
services:
  bibliothecarius:
    build: ./bibliothecarius
    volumes:
      - './bibliothecarius/config:/config'
    ports:
      - '8080:8080'
  qdrant:
    volumes:
      - './qdrant/data:/qdrant/storage'
    ports:
      - '6333:6333'
    image: qdrant/qdrant

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 
```
这个是我的本地的配置，一起全部启动的
@Casper-ren
